### ISSUE TITLE
<> (exchange) symbol - Original or not ?

### ISSUE THREAD

**Issue by pc1211** [zathras/jrpn#112]
Hello,

Was it a deliberate choice (readability ?) to change the original exchange symbol (for x<>y and x<->) of the HP-15C ? 
I prefer the original but it's up to you ... Thanks anyway for your app

**Comment by zathras** [comment]
Yes.  I found a freely-available font that looked pretty good, but I couldn't find any really good glyphs for exchange.  There's a Unicode symbol that is theoretically closer to what I see on my 15C's key, but it looked awful, at least with that font (and a couple of others I tried).  Without resorting to designing my own font (or doing the equivalent with drawing operations), rendering will always be approximate.  See also the sigma symbol, the font of the "x" and the "y" on the exchange key, etc.

**Comment by pc1211** [comment]
Hello,

It could be interesting to use the PDF file of the 15C Collector's Edition Owner's Handbook (mine is Edition 3, February 2023) because it contains good **vector** images of the keys: I zoomed the "x<>y" image, took screenshot, got path with GIMP, and exported it to the **SVG** attached here (8 Kb). I could do it for you for each key if you want. Why not ?

![hps3](https://github.com/user-attachments/assets/0d41ade6-6900-4491-9a8c-22f947162270)

**Comment by zathras** [comment]
Hmmm...  That's a creative solution.  Frankly, doing that for all the keys feels like overkill.  I could see making some kind of exception for the exchange key, since that one stands out a lot more than the others.  But also, I was very careful to keep JRPN cleanroom - not out of fear of being sued or anything, just out of general principles.  Surely the Owner's Handbook is copyrighted.
