### ISSUE TITLE
Auto-save state on app lifecycle events (only works on mobile)

### ISSUE THREAD

**Issue by billf-pshs** [zathras/jrpn#46]
The current functionality of not automatically saving state is pretty hacky.  `RestorationManager` looks like it's the intended Flutter mechanism to deal with this.

In my defense, back when I wrote JRPN, I did look pretty hard to find reliable app lifecycle state notifications, and I eventually gave up.  `RestorationManager` isn't exactly obvious, or prominent.

**Comment by zathras** [comment]
Hey, neat!  `RestorationManager` doesn't work on Linux!  (Probably not on desktop at all, though I didn't try).  Verified with `flutter create --sample=widgets.RestorableValue.1 foo`.

Also, verified that app lifecycle notifications don't work on Linux -- no notification is given when closing the app (by pressing on the X button in the window manager).

So:  It was a nice thought.  I guess I *could* make automatic state saving work on Android only, but introducing differing behaviors on different platforms is bad in its own way.  Also, the whole `RestorationManager` dance is pretty complicated and slow, from what I can see.  Maybe app lifecycle notifications work on Android, or maybe they sometimes work on Android.  Or mostly?

Hmmm.  Yes, app lifecycle events do work on Android.  I'm sure this duplicates what I figured out when I first looked into this :-)  So I *could* auto-save the state on Android, but not on desktop.  Maybe that's justifiable, since on Desktop you (mostly) have to explicitly close the app via the window manager in order to get the non-saving behavior.

**Comment by billf-pshs** [comment]
Flutter enhancement request for desktop:  https://github.com/flutter/flutter/issues/30735  There is a package called `flutter_window_close`, but it doesn't play well with MacOS and multiple windows.

**Comment by zathras** [comment]
Released in 2.1.5

**Comment by billf-pshs** [comment]
With Flutter 3.13.0, they've added `AppLifecycleListener()`.  It looks like the main thing this adds is the ability to do something when the window is closed on desktop (at least on MacOS -- I haven't verified on Windows or Linux).

**Comment by zathras** [comment]
Extension to desktop released in 2.1.7
