### ISSUE TITLE
website apk's are signed with a debug key

### ISSUE THREAD

**Issue by johanw666** [zathras/jrpn#71]
Both the Android apk's of jrpn 15 and 16 as distributed on the website are signed with a debug key so they can't be installed over 2.1.9 unless you uninstall that version first.

**Comment by zathras** [comment]
Yes,  That's not a bug.  The preferred installation route is the play store.  I just make the raw APKs in case someone really wants to install it manually, outside Google's ecosystem.

**Comment by johanw666** [comment]
I prefer to install it outside Google, and I also prefer to store the apk's in case of a regression or Google removing something, and Aurora Store downloads via Google but only as splity apk's. But I'll try something else.

**Comment by zathras** [comment]
Oh, well, if you're comfortable building from source, the way to do that is from the jrpn github repo (and not jrpn15_build).  That way, you can sign with your own, consistent debug key.

Just go into jrpn/jrpn15, and type "flutter build apk".  Or even just "flutter run --release" -- it installs for you.

The reason why the jrpn15_build repo exists is because for Linux (and now Windows and Mac), I use an external build machine.   For Linux I'm kind of forced to use Canonical's, which isn't all that configurable, so it was just a whole lot easier having one repo per app (one for 15, and one for 16).  Once I did that, I kept with that pattern for Windows and Mac, even though GitHub actions are more configurable, because it was easier.

For Android, I build manually, because using a cloud build machine would have meant putting my Google app store private key on someone else's computer.  Making sure I did that securely requires thought, and the cloud provider could eventually be hacked.

I actually install the calculator on my phone using the play store, so I can tell when it publishes, and do a quick smoke test.
