### ISSUE TITLE
jrpn 15 2.1.10 crashes on start

### ISSUE THREAD

**Issue by johanw666** [zathras/jrpn#72]
**JRPN 16C or 15C?**
jrpn 15 2.1.10

**Describe the bug**
When I install jrpn 2.1.10 it crashes at startup.

**Debug Log**
System log shows these errors:

```
01-21 10:08:07.295 I/PackageUpdatedTask(5384): mAllAppsList.updatePackage com.jovial.jrpn15
01-21 10:08:07.300 W/ActivityManager(4585): Unable to start service Intent { act=com.google.android.gms.ads.identifier.service.START pkg=com.google.android.gms } U=0: not found
01-21 10:08:07.304 E/Ads     (324): Fail to get isAdIdFakeForDebugLogging
01-21 10:08:07.304 E/Ads     (324): java.io.IOException: Connection failure
01-21 10:08:07.304 E/Ads     (324): 	at com.google.android.gms.ads.identifier.d.d(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:160)
01-21 10:08:07.304 E/Ads     (324): 	at com.google.android.gms.ads.internal.util.c.a(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:11)
01-21 10:08:07.304 E/Ads     (324): 	at com.google.android.gms.ads.internal.util.a.run(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:11)
01-21 10:08:07.304 E/Ads     (324): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
01-21 10:08:07.304 E/Ads     (324): 	at m.cdl.a(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:3)
01-21 10:08:07.304 E/Ads     (324): 	at m.cct.run(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:21)
01-21 10:08:07.304 E/Ads     (324): 	at m.cdm.run(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:5)
01-21 10:08:07.304 E/Ads     (324): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-21 10:08:07.304 E/Ads     (324): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-21 10:08:07.304 E/Ads     (324): 	at java.lang.Thread.run(Thread.java:923)
01-21 10:08:07.304 W/Ads     (324): Update ad debug logging enablement as false
```
Why does it even want to read an advertising ID? Due to the apk being signed with a debug key?

**Platform:**
Android 11, play store not available and advertising service in Google Play services disabled.

**Comment by zathras** [comment]
Interesting.  I don't know what's going on here...  The update to JRPN 15 was rejected by the play store, too.  Maybe for the same reason?  In my code, I don't do anything with ad IDs, or anything like that.  This might be related.

**Comment by zathras** [comment]
OK, it looks like the advertising ID thing is a red herring.  That's deep in Google's code.  I note that it says "Update ad debug logging enablement as false", which is fine by me, since I'm not doing ads of any kind.

The reason this APK isn't working is because the Flutter android project I was using for that build was badly obsolete.  I switched to using a Github workflow for the debug APK I was publishing on github, and the setup was a little different, in a way that made me use obsolete Android code that the Flutter dev environment had auto-generated.

I think the fix for this for now is for me to just remove the debug APKs from github.  Once I get the play store issue resolved, do you need a debug APK from github for anything?  I might just stop publishing them, since it adds a step for little benefit, and it causes confusion.

**Comment by johanw666** [comment]
That probably explains why I could not compile it myself, getting an error about mismatching Kotlin versions in libraries.

**Comment by zathras** [comment]
SEe https://github.com/zathras/jrpn/issues/71#issuecomment-1903629429
