### ISSUE TITLE
ISZ/DSZ don't always increment/decrement

### ISSUE THREAD

**Issue by ricknun** [zathras/jrpn#97]
**JRPN 16C or 15C?**
JRPN 16C

**Describe the bug**
ISZ/DSZ done manually on the keyboard should change reg I contents, and don't.

**To Reproduce**
1 STO I ISZ RCL I (see 1 and the real HP-16C displays 2).  Similar for DSZ.

**Platform:**
Windows 10

**Comment by zathras** [comment]
@ricknun When done from the keyboard on the real calculator, does it also increment the current line number if the skip condition is true?

**Comment by ricknun** [comment]
Done on my real HP-16C:
2 STO I P/R (see line 007 of a program) P/R
DSZ (2->1) P/R (see line 007) P/R
DSZ (1->0) P/R (see line 008) P/R
DSZ (0->-1) P/R (see line 008) P/R

-2 STO I P/R (see line 008) P/R
ISZ (-2->-1) P/R (see line 008) P/R
ISZ (-1->0) P/R (see line 009) P/R
ISZ (0->1) P/R (see line 009) P/R

**Comment by zathras** [comment]
Interesting!  Is the same true for the conditional tests, like "x = 0"?  (No need to test all eight; I'm sure they're all the same.)

For ISZ/DSZ, there's language in the user manual that says "If a program is running, ...."  It doesn't say what happens if a program isn't running, but I remember taking that text to imply that ISZ/DSZ, and by extension all the conditional instructions would be a NOP if a program weren't running.  But I guess not.  Before I remove that code, it would be good to verify that "x = 0" increments the program counter when entered from the keyboard and x isn't 0.

Assuming this is true across the board, it's actually a simplification.

**Comment by ricknun** [comment]
Real HP-16C again, checked twice.
P/R (see program line 007) P/R
1 ENTER X=0? P/R (see line 008) P/R
0 ENTER X=0? P/R (see line 008) P/R
1 ENTER X=0? P/R (see line 009) P/R

**Comment by zathras** [comment]
Thanks!  I double-checked with g-x=0 on my (original) 15C, and same deal -- it should execute outside a program, too, incrementing the program counter if the condition isn't met.

**Comment by zathras** [comment]
Released in 2.1.14
